# Development environment overrides
global:
  namespace: vikareta-dev

services:
  admin:
    replicaCount: 1
    image:
      tag: develop
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
        
  backend:
    replicaCount: 1
    image:
      tag: develop
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    env:
      - name: NODE_ENV
        value: "development"
        
  dashboard:
    replicaCount: 1
    image:
      tag: develop
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
        
  web:
    replicaCount: 1
    image:
      tag: develop
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi