name: vikareta-web
namespace: vikareta

image:
  repository: ghcr.io/aryannkumar/vikareta-web
  tag: main
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

imagePullSecrets:
  - name: ghcr-secret

env: []

nodeSelector: {}
tolerations: []
affinity: {}