name: vikareta-backend
namespace: vikareta

image:
  repository: ghcr.io/aryannkumar/vikareta-backend
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: ghcr-secret

envFrom:
  - configMapRef:
      name: backend-config

env:
  - name: NODE_ENV
    value: "production"

livenessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 5

migration:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}