{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}-service
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: {{ $serviceName }}
    app.kubernetes.io/part-of: vikareta-platform
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $service.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}